name: 3-hour Crypto Scanner

on:
  schedule:
    - cron: "0 */3 * * *"   # runs every 3 hours
  workflow_dispatch:        # allows manual run from Actions tab

jobs:
  run-scanner:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests pandas ta

    - name: Run scanner
      env:
        EMAIL_FROM: ${{ secrets.EMAIL_FROM }}
        EMAIL_PASS: ${{ secrets.EMAIL_PASS }}
        EMAIL_TO: ${{ secrets.EMAIL_TO }}
      run: |
        python scanner_github.py
